Repository AY2021S2-CS2103-T14-1/tp, pull requests merged in 2021-03, with the labels that each got.

#62 Add issue feature
  .vscode/settings.json
  docs/UserGuide.md
  eclipse-formatter.xml
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/DeleteIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/FindIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/ListIssueCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/issue/AddIssueCommandParser.java
  src/main/java/seedu/address/logic/parser/issue/DeleteIssueCommandParser.java
  src/main/java/seedu/address/logic/parser/issue/EditIssueCommandParser.java
  src/main/java/seedu/address/logic/parser/issue/FindIssueCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/issue/Category.java
  src/main/java/seedu/address/model/issue/Description.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/issue/IssueList.java
  src/main/java/seedu/address/model/issue/IssueStatus.java
  src/main/java/seedu/address/model/issue/RoomNumber.java
  src/main/java/seedu/address/model/issue/RoomNumberContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/issue/Status.java
  src/main/java/seedu/address/model/issue/Timestamp.java
  src/main/java/seedu/address/model/issue/exceptions/InvalidIssueStatusException.java
  src/main/java/seedu/address/model/issue/exceptions/IssueNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedIssue.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/IssueCard.java
  src/main/java/seedu/address/ui/IssueListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/IssueListCard.fxml
  src/main/resources/view/IssueListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateResidentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidResidentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalResidentsAddressBook.json
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#63 Add command history
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/MathUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewHistoryCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/commandhistory/CommandHistory.java
  src/main/java/seedu/address/model/commandhistory/CommandHistoryEntry.java
  src/main/java/seedu/address/model/commandhistory/ReadOnlyCommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewHistoryCommandParserTest.java
  src/test/java/seedu/address/model/commandhistory/CommandHistoryEntryTest.java
  src/test/java/seedu/address/model/commandhistory/CommandHistoryTest.java
  src/test/java/seedu/address/testutil/TypicalCommandHistoryEntries.java
Labels: priority.Medium, type.Story

#73 Fix minor variable names and timestamp format in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/DeleteIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/ListIssueCommand.java
  src/main/java/seedu/address/logic/parser/issue/EditIssueCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
Labels: severity.VeryLow, type.Documentation

#72 Fix resident example message
  src/main/java/seedu/address/logic/commands/resident/AddResidentCommand.java
  src/main/java/seedu/address/logic/commands/resident/EditResidentCommand.java
  src/main/java/seedu/address/model/resident/Resident.java
  src/main/java/seedu/address/ui/ResidentCard.java
Labels: severity.VeryLow, type.Documentation

#65 Add alias command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Alias.java
  src/main/java/seedu/address/commons/core/AliasMapping.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AliasCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium, type.Story

#75 Remove person references in Javadocs for Room methods
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/RoomNumber.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/main/java/seedu/address/model/room/exceptions/DuplicateRoomException.java
  src/main/java/seedu/address/storage/room/JsonAdaptedRoom.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/test/java/seedu/address/testutil/room/RoomBuilder.java
  src/test/java/seedu/address/testutil/room/RoomUtil.java
Labels: severity.VeryLow, type.Documentation

#78 Command History: Add missing UG entry
  docs/UserGuide.md
Labels: severity.Medium, type.Documentation

#74 fix(ug): Update prefixes for add/edit room commands
  docs/UserGuide.md
Labels: severity.VeryLow, type.Documentation

#80 Fix DG Use Case Formatting
  docs/DeveloperGuide.md
Labels: severity.VeryLow, type.Documentation

#81 Fix duplicate prefixes error
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: severity.Medium, type.Bug

#83 Change app title to "SunRez"
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#101 Enable assertions in build.gradle
  build.gradle
Labels: type.Task

#104 Refactor Command History
  src/main/java/seedu/address/commons/core/AliasMapping.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commandhistory/CommandHistorySelector.java
  src/main/java/seedu/address/logic/commandhistory/SuppliedCommandHistorySelector.java
  src/main/java/seedu/address/logic/commands/commandhistory/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/commandhistory/ViewHistoryCommandParser.java
  src/main/java/seedu/address/model/commandhistory/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewHistoryCommandParserTest.java
Labels: severity.VeryLow, type.Enhancement

#109 Add command history design details to DG
  docs/DeveloperGuide.md
  docs/diagrams/commandhistory/CmdHistAccessHistorySequenceDiagram.puml
  docs/diagrams/commandhistory/CmdHistModelClassDiagram.puml
  docs/diagrams/commandhistory/CmdHistStorageSequenceDiagram.puml
  docs/diagrams/commandhistory/CmdHistUpdateSequenceDiagram.puml
  docs/diagrams/commandhistory/CmdHistViewHistorySequenceDiagram.puml
  docs/images/commandhistory/CmdHistAccessHistorySequenceDiagram.png
  docs/images/commandhistory/CmdHistModelClassDiagram.png
  docs/images/commandhistory/CmdHistStorageSequenceDiagram.png
  docs/images/commandhistory/CmdHistUpdateSequenceDiagram.png
  docs/images/commandhistory/CmdHistViewHistorySequenceDiagram.png
Labels: priority.High, type.Documentation

#115 Add Room and AddRoomCommand implementation details to DG
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/diagrams/room/AddRoomCommandActivityDiagram.puml
  docs/diagrams/room/AddRoomCommandSeqDiagram.puml
  docs/diagrams/room/RoomClass.puml
  docs/images/room/AddRoomCommandActivityDiagram.png
  docs/images/room/AddRoomCommandSeqDiagram.png
  docs/images/room/RoomClass.png
Labels: priority.High, type.Documentation

#116 Add Alias implementation details to DG
  docs/DeveloperGuide.md
  docs/diagrams/alias/AliasCreationSequenceDiagram.puml
  docs/diagrams/alias/AliasExecutionActivityDiagram.puml
  docs/images/alias/AliasCreationSequenceDiagram.png
  docs/images/alias/AliasExecutionActivityDiagram.png
Labels: priority.High, type.Documentation

#103 Add implementation details in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/residentroom/ResidentRoomAllocationDiagram.puml
  docs/images/residentroom/ResidentRoomAllocationDiagram.png
Labels: priority.High, type.Documentation

#130 Docs(CommandHistory): Fix UG case inconsistency
  docs/UserGuide.md
Labels: severity.VeryLow, type.Documentation

#119 Add close issue command
  src/main/java/seedu/address/logic/commands/issue/CloseIssueCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/issue/CloseIssueCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/issue/Issue.java
  src/main/java/seedu/address/model/issue/IssueList.java
  src/main/java/seedu/address/model/issue/Status.java
Labels: priority.Medium

#118 Add launch.json with assertions for VS Code
  .vscode/launch.json
Labels: priority.Medium

#107 Add command history storage
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commandhistory/CommandHistorySelector.java
  src/main/java/seedu/address/logic/commandhistory/SuppliedCommandHistorySelector.java
  src/main/java/seedu/address/logic/commands/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/commands/commandhistory/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/ViewHistoryCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/commandhistory/CommandHistory.java
  src/main/java/seedu/address/model/commandhistory/CommandHistoryEntry.java
  src/main/java/seedu/address/model/commandhistory/ReadOnlyCommandHistory.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/commandhistory/CommandHistoryStorage.java
  src/main/java/seedu/address/storage/commandhistory/PlainTextCommandHistoryStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium, type.Story

#139 Fix locale issue for test
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/model/issue/Timestamp.java
Labels: severity.High, type.Bug

#128 Add Undo/Redo commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/issue/AddIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/DeleteIssueCommand.java
  src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
  src/main/java/seedu/address/logic/commands/resident/AddResidentCommand.java
  src/main/java/seedu/address/logic/commands/resident/DeleteResidentCommand.java
  src/main/java/seedu/address/logic/commands/resident/EditResidentCommand.java
  src/main/java/seedu/address/logic/commands/room/AddRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/DeleteRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/commands/undoredo/RedoCommand.java
  src/main/java/seedu/address/logic/commands/undoredo/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/undoredo/StatefulAddressBook.java
  src/main/java/seedu/address/model/undoredo/exceptions/NoRedoableStateException.java
  src/main/java/seedu/address/model/undoredo/exceptions/NoUndoableStateException.java
  src/main/java/seedu/address/model/undoredo/exceptions/RedoException.java
  src/main/java/seedu/address/model/undoredo/exceptions/UndoException.java
  src/main/java/seedu/address/ui/KeyboardShortcuts.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddResidentCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/room/AddRoomCommandTest.java
Labels: priority.Medium, type.Story

#151 Rename output files
  build.gradle
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: severity.VeryLow, type.Bug

#149 Fix(CommandResult): Fix Code Style
  src/main/java/seedu/address/logic/commands/CommandResult.java
Labels: severity.High, type.Documentation

#152 UI: Change layout and update icon
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/sunrez_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Medium, type.Enhancement

#153 Docs: Update landing page and README
  README.md
  docs/images/Ui.png
  docs/index.md
Labels: priority.High, type.Documentation

#160 Docs(UG): Add feature sections and update data transfer instructions
  docs/UserGuide.md
Labels: priority.High, type.Documentation
