Repository AY2021S2-CS2103-T14-1/tp, pull requests merged in 2021-04, with the labels that each got.

#279 UG: Add parameters section
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#286 Close #244: Add TAG parameter specifications
  docs/UserGuide.md
Labels: severity.VeryLow, type.Documentation

#283 Fix #219: Remove room no. from radd and redit
  docs/UserGuide.md
Labels: severity.High, type.Bug, type.Documentation

#282 Fix #217: Increase window min height
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, type.Bug

#281 Fix #201: Change string references of address book to SunRez
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/issue/EditIssueCommand.java
  src/main/java/seedu/address/logic/commands/resident/AddResidentCommand.java
  src/main/java/seedu/address/logic/commands/resident/EditResidentCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: severity.Low, type.Bug

#277 Fix #255: Add meaning of GUI to intro
  docs/UserGuide.md
Labels: priority.Low, type.Documentation

#299 Close #253: Add column headers
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Enhancement

#300 Close #226: Decrease minimum card size
  src/main/resources/view/IssueListCard.fxml
  src/main/resources/view/ResidentListCard.fxml
  src/main/resources/view/RoomListCard.fxml
Labels: priority.Low, type.Enhancement

#306 Add parameters summary section in UG
  docs/Gemfile.lock
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#311 Fix #310: Support alias and unalias commands
  src/main/java/seedu/address/logic/commands/alias/AliasCommand.java
  src/main/java/seedu/address/logic/commands/alias/UnaliasCommand.java
Labels: severity.Medium, type.Bug

#309 Fix #202: Update product image
  docs/images/Ui.png
Labels: severity.VeryLow, type.Bug, type.Documentation

#308 Close #303: Add text wrap to result box
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium, type.Enhancement

#317 DG: Update Command History section
  docs/DeveloperGuide.md
  docs/diagrams/commandhistory/CmdHistModelClassDiagram.puml
  docs/diagrams/commandhistory/CmdHistStorageSequenceDiagram.puml
  docs/diagrams/commandhistory/CommandHistoryStorageActivityDiagram.puml
  docs/images/commandhistory/CmdHistModelClassDiagram.png
  docs/images/commandhistory/CmdHistStorageSequenceDiagram.png
  docs/images/commandhistory/CommandHistoryStorageActivityDiagram.png
Labels: priority.High, type.Documentation

#301 Close #198: Update Benedict's responsibilities in About Us
  docs/AboutUs.md
Labels: priority.Medium, type.Documentation

#297 Fix #257: Unbold example commands in quick start
  docs/UserGuide.md
Labels: severity.VeryLow, type.Documentation

#335 Fix #334: Update COUNT param in UG to be specific
  docs/UserGuide.md
Labels: priority.Low, type.Documentation

#336 Docs(UG): Move Quick Start section to just after intro
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#333 Docs(DG): Add manual test cases for command history and undo/redo
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#343 Docs(PPP): Add Benedict's PPP
  docs/AboutUs.md
  docs/team/benedict.md
  docs/team/benedictkhoomw.md
Labels: priority.High, type.Documentation

#379 Fix #362: Standardize error messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/commandhistory/ViewHistoryCommand.java
  src/main/java/seedu/address/logic/parser/commandhistory/ViewHistoryCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewHistoryCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewHistoryCommandParserTest.java
Labels: priority.Medium, type.Bug

#383 Docs(DG): Update storage diagram and add alias diagram/manual testing
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/alias/AliasMappingClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/alias/AliasMappingClassDiagram.png
Labels: priority.High, type.Documentation

#401 Fix: Prevent getRandomEntry from generating an empty string
  src/test/java/seedu/address/testutil/TypicalCommandHistoryEntries.java
Labels: severity.Medium, type.Bug

#378 Docs(PPP): Colin
  docs/AboutUs.md
  docs/team/colin.md
  docs/team/colintkn.md
Labels: priority.High, type.Documentation

#400 Docs: Update product image
  docs/images/Ui.png
Labels: priority.High, type.Documentation

#409 Docs(UG): Update find commands and param justification
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#386 Docs(DG): Update Logic component section
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.High, type.Documentation

#408 Docs(DG): Add sub-section explaining diagram color scheme
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#419 Docs(DG): Add full-length version of API on first use
  docs/DeveloperGuide.md
Labels: type.Documentation

#418 Docs(DG): Add logic class diagram note
  docs/DeveloperGuide.md
Labels: type.Documentation

#407 Update DG diagram and storage interface
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/alias/AliasMappingClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/alias/AliasMappingClassDiagram.png
  src/main/java/seedu/address/storage/Storage.java
Labels: priority.Medium, type.Documentation

#429 Docs(DG): Add subsection on parsing and execution
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: type.Documentation

#417 Docs(DG): Update command history section
  docs/DeveloperGuide.md
  docs/diagrams/commandhistory/CmdHistAccessHistorySequenceDiagram.puml
  docs/diagrams/commandhistory/CmdHistModelClassDiagram.puml
  docs/diagrams/commandhistory/CmdHistUpdateSequenceDiagram.puml
  docs/diagrams/commandhistory/CmdHistViewHistorySequenceDiagram.puml
  docs/diagrams/commandhistory/CommandHistoryStorageActivityDiagram.puml
  docs/images/commandhistory/CmdHistAccessHistorySequenceDiagram.png
  docs/images/commandhistory/CmdHistModelClassDiagram.png
  docs/images/commandhistory/CmdHistUpdateSequenceDiagram.png
  docs/images/commandhistory/CmdHistViewHistorySequenceDiagram.png
  docs/images/commandhistory/CommandHistoryStorageActivityDiagram.png
Labels: type.Documentation

#433 Fix #432
  docs/DeveloperGuide.md
Labels: type.Documentation

#438 AboutUs: Update names to match Luminus
  docs/AboutUs.md
Labels: type.Documentation

#442 Docs(DevOps): Fix codecov link
  docs/DevOps.md
Labels: severity.Low, type.Documentation

#425 Docs(PPP): Updates Linh's PPP
  docs/team/cnlinh.md
Labels: type.Documentation

#411 Docs(PPP): Update Benedict's PPP
  docs/team/benedictkhoomw.md
Labels: type.Documentation

#443 Docs(DG): Add effort section
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#444 Docs(PPP): Update Benedict's PPP
  docs/team/benedictkhoomw.md
Labels: type.Documentation

#446 Docs(Favicon): Fix favicon in PPPs
  docs/_includes/head.html
Labels: type.Documentation

#448 Docs(UG): Update data transfer instructions
  docs/UserGuide.md
Labels: type.Documentation

#450 Update Javadocs
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/KeyboardShortcuts.java
Labels: type.Documentation

#449 Docs(Room): Update JavaDocs for Room
  src/main/java/seedu/address/logic/commands/room/AddRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/DeleteRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/ListRoomCommand.java
  src/main/java/seedu/address/logic/parser/room/AddRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/DeleteRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/FindRoomCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/IsOccupied.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/RoomNumber.java
  src/main/java/seedu/address/model/room/RoomType.java
  src/main/java/seedu/address/model/room/RoomTypeOptions.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/room/AddRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/DeleteRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomDescriptorTest.java
  src/test/java/seedu/address/logic/commands/room/ListRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/RoomCommandTestUtil.java
  src/test/java/seedu/address/model/room/RoomNumberTest.java
  src/test/java/seedu/address/model/room/RoomOccupancyTest.java
  src/test/java/seedu/address/model/room/RoomTest.java
  src/test/java/seedu/address/model/room/UniqueRoomListTest.java
Labels: type.Documentation
